driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-10.04
    run_list:
      - recipe[apt::default]
  - name: debian-7.6
  - name: centos-6.5
  - name: centos-5.10

suites:
  - name: default
    run_list:
      - recipe[ucspi-tcp::default]
  - name: source
    # don't retest centos, it's a source install by default
    excludes: [centos-6.5, centos-5.10]
    run_list:
      - recipe[ucspi-tcp::default]
    attributes:
      ucspi:
        install_method: source
